added feature
noftaly/MonkaBot pull request #2
Opened 2021-05-03 09:14 UTC by Kethash

1.0.0
We probabily need to change how the eProf would be pinged

2021-05-05 09:42 UTC, noftaly requested changes
Hey :) Merci pour la PR ! Il y a quelques changements à faire. Je te laisse en tout premier accepter mes suggestions (bouton "Commit suggestion") en dessous puis appliquer les reviews :)

Il faudrait aussi bouger le fichier de `./config/profs.ts` vers `./src/lib/structures/profs.ts`.

Merci ! 🚀

2021-05-05 09:42 UTC, noftaly commented on src/events/messageReactionAdd.ts
> +      await eProf.send(`${member} needs you in ${message.channel}`);
Il faudrait mettre les messages en français :) (et les fournir un peu plus pour qu'ils donnent plus d'informations)

2021-05-05 09:42 UTC, noftaly commented on config/profs.ts
> +        physique: ['808432662732996628', '808432809697345606', '808432842249076808'],
Il faut mettre la configuration dans `./config/settings.ts`, dans un objets `channels`. Comme ca quand on doit les changer on peut juste tout changer dans settings, pas besoin de jongler entre les fichiers :)

2021-05-05 09:42 UTC, noftaly commented on config/profs.ts
> +        physique: 'eProfPhysiqueId',
Il faudrait utiliser l'ID des rôles, et les mettre dans la configuration dans `./config/settings.ts`. Comme ca quand on doit les changer on peut juste tout changer dans settings, pas besoin de jongler entre les fichiers :)

2021-05-05 09:42 UTC, noftaly commented on config/profs.ts
> +    laMap: Map<string[], string>;
Faudrait trouver un autre nom que `laMap` 😅

2021-05-05 09:42 UTC, noftaly commented on config/profs.ts
> +                return this.laMap.get(i[0]);
optimisable :
```suggestion
        for (const [matieresId, eProfId] of this.laMap) {
            if (matieresId.includes(channelId))
                return eProfId;
```

2021-05-05 09:42 UTC, noftaly commented on config/profs.ts
> +    findProf: Find = (channelId: string): string => {
Il faudrait directement en faire une méthode. Tu peux donc supprimer le type tout en haut du fichier :)
```suggestion
    public findProf(channelId: string): string {
```

2021-05-08 08:54 UTC, Kethash commented on config/profs.ts
> +        physique: ['808432662732996628', '808432809697345606', '808432842249076808'],
Fait !

2021-05-08 08:54 UTC, Kethash commented on config/profs.ts
> +        physique: 'eProfPhysiqueId',
Fait !

2021-05-08 08:56 UTC, Kethash commented on config/profs.ts
> +    laMap: Map<string[], string>;
Renommé en coursesAndProfs !

2021-05-08 09:30 UTC, Kethash reviewed
Les modifications ont été apportés

2021-05-08 09:31 UTC, Kethash commented on src/events/messageReactionAdd.ts
> +      await eProf.send(`${member} needs you in ${message.channel}`);
C'est fait !

2021-05-08 09:52 UTC, noftaly requested changes
Merci ! Plus que ces 2 petits changements ;)

2021-05-08 09:52 UTC, noftaly commented on src/events/messageReactionAdd.ts
> +    }
Il faudrait enlever le premier commentaire, et mettre à jour les messages en français :)
Concernant le MP (`await eProf.send(...)`) : il y a des chances que le mec ai les MPs fermés. Auquel cas ca va lancer une erreur. Sauf que c'est un comportement normal donc on ne veut pas lancer d'erreur, on juste juste "fail en silence" et tant pis pour le MP. Pour ca il faudrait que tu `catch` la promesse et que tu ne fasses rien dans le catch. Il faudrait rajouter un .catch(noop)` à la fin de la ligne (et tu peux importer `noop` de `utils`, c'est fait pour ca :) )

2021-05-08 09:52 UTC, noftaly commented on config/settings.ts
> +      physique: 'eProfPhysiqueId',
Faudrait utiliser les IDs des rôles :)

2021-05-08 20:36 UTC, Kethash commented on config/settings.ts
> +      physique: 'eProfPhysiqueId',
Justement je ne les ai pas, on les a eu quelque-part ou faut que j'aille demander ?

2021-05-08 20:39 UTC, noftaly commented on config/settings.ts
> +      physique: 'eProfPhysiqueId',
laisse des strings vide alors (mais modifie le code en accordance car c'est des ids maintenant), parce qu'ultimement il faudrait le stocker en BDD (via la commande `!setup`). Pour le moment pas grave, celui qui utilise le bot devra les remplir lui même.

j'ajouterai (ou tu le feras stv) les IDs en bdd plus tard, c'est pas très grave en attendant

2021-05-08 20:48 UTC, Kethash commented on config/settings.ts
> +      physique: 'eProfPhysiqueId',
J'ai laissé les strings vides,
Je vais te laisser faire j'ai peur de faire une connerie x)

2021-05-08 20:51 UTC, Kethash commented on src/events/messageReactionAdd.ts
> +    }
Les changements ont été effectués !

2021-05-09 09:42 UTC, merged

2021-05-09 09:42 UTC, noftaly commented
Merci ! 🚀