Interprétation LaTeX par le bot lui-même
noftaly/MonkaBot pull request #97
Opened 2023-10-25 22:40 UTC by Niilyx

Pour ça j'utilise [MathJax](https://www.npmjs.com/package/mathjax) pour le parsing des formules LaTeX et [Sharp](https://www.npmjs.com/package/sharp) pour la conversion en un .png

Il reste un problème à fix, sur certaines formules test, MathJax échoue le parsing et en réessayant tout de suite après, il y parvient.

Exemple de formule problématique :
```
\begin{align*}
\sum\limits_{k=1}^n u_k
&= \sum\limits_{k=1}^n (\frac{2}{k} - \frac{2}{k+2}) \\ 
&= \sum\limits_{k=1}^n \frac{2}{k} - \sum\limits_{k=1}^n \frac{2}{k+2} \\
&= \sum\limits_{k=1}^n \frac{2}{k} - \sum\limits_{k=3}^{n+2} \frac{2}{k} \\
&= \sum\limits_{k=3}^n \frac{2}{k} +2 +1 - (\sum\limits_{k=3}^{n} \frac{2}{k} + \frac{2}{n+1} + \frac{2}{n+2}) \\
&= \textcolor{blue}{\sum\limits_{k=3}^n \frac{2}{k}} + 3 \textcolor{blue}{- \sum\limits_{k=3}^{n} \frac{2}{k}} - \frac{2}{n+1} - \frac{2}{n+2} \\
&= 3 - \frac{2}{n+1} - \frac{2}{n+2}     \end{align*}
```
c'est-à-dire : 
![image](https://github.com/horizon-efrei/HorizonBot/assets/43385037/223e6a94-1f2d-41b3-a850-6d0757f0344f)

Si vous avez une idée pour fix ça, où une meilleure librairie de parsing à proposer, je suis tout ouïe

2023-10-31 01:05 UTC, Niilyx commented
Bientôt y aura quelque chose d'autre qui arrivera :eyes:

2023-11-10 19:34 UTC, noftaly requested changes
Merci beaucoup pour la PR et d'avoir pris le temps de trifouiller MathJax !
Quelques petites suggestions à prendre en compte, hésite pas à me contacter sur discord si t'as des questions, ou à répondre aux commentaires direct sur GitHub

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +continue;
`eslint/indent` est buggé, mais ici faut bien indenter le `continue`.

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +    // Explicitement bypass le readonly et effectivement faire un await dans à l'initialisation
[Commentaire en anglais please](https://github.com/horizon-efrei/HorizonBot/blob/bcda527400e960b4b3e91eaaf8a3eb0c15793ca2/CONTRIBUTING.md?plain=1#L32-L34)

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +        right: pad,
J'ai un peu expérimenté de mon côté, et tu penses quoi ce ça ? C'est un bon compromis je pense, qui scale en fonction de la taille de l'équation (avec un max à 1024). Ça rend pas trop mal, je te laisse tester

```suggestion
    return sharp(Buffer.from(svgText))
      .resize({ width: Math.min(Math.floor(6 * equation.length), 1024) })
      .extend({
        top: 10,
        bottom: 10,
        left: 10,
        right: 10,
```

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +      .flatten({ background: '#FFF' }) // Arrière-plan de couleur
Commentaire en anglais please

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
>    }
L'idéal serait que cette fonction return un `Promise<Buffer>` et que ce soit le `chatInputRun` qui s'occupe de la lancer.
Ça a plusieurs avantages, déjà pas besoin de passer le replyTo à cette fonction, et ensuite si on veut la réutiliser pour qqch d'autre ce sera plus simple de la réutiliser/l'extraire dans un `utils/`.
Tu peux aussi en profiter pour rajouter une valeur par défaut au paramètre attempt : `attempt = 0`, comme ca pas besoin de la spécifier quand on l'appelle depuis `chatInputRun`.

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +        });
Il faudrait les passer dans la configuration.
Le deuxième est straightforward, pour le premier faudra utiliser `pupa`. je te laisse regarder comment est-ce qu'on fait dans d'autres commandes, mais il faudrait en gros rajouter deux entrées dans [l'objet de config](https://github.com/horizon-efrei/HorizonBot/blob/bcda527400e960b4b3e91eaaf8a3eb0c15793ca2/config/commands/general.ts#L71-L72), puis ici faire un `this.messages.{le nom de l'entrée}` (l'autocomplétion TypeScript pourra bien t'aider).

Exemple dans le fichier de la commande ping: [commande](https://github.com/horizon-efrei/HorizonBot/blob/bcda527400e960b4b3e91eaaf8a3eb0c15793ca2/src/commands/General/ping.ts#L26) - [config](https://github.com/horizon-efrei/HorizonBot/blob/bcda527400e960b4b3e91eaaf8a3eb0c15793ca2/config/commands/general.ts#L98C62-L98C62)

2023-11-10 19:34 UTC, noftaly commented on src/commands/General/latex.ts
> +  private readonly _mathJax: any = require('mathjax').init({
Utilise un `import` et pas un `require`
Tu peux notamment faire un `import { init as initMathJax } from 'mathjax';` par exemple, puis ici appeler la fonction  `initMathjax`. Hésite pas à rajouter des disable d'eslint ou de typescript car mathjax est typé avec le cul

2023-11-10 20:55 UTC, noftaly approved these changes
LGTM 🚀
Merci beaucoup !

2023-11-10 21:07 UTC, merged